// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SystemStats.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadAvgStat struct {
	LoadAvg              float32  `protobuf:"fixed32,1,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadAvgStat) Reset()         { *m = LoadAvgStat{} }
func (m *LoadAvgStat) String() string { return proto.CompactTextString(m) }
func (*LoadAvgStat) ProtoMessage()    {}
func (*LoadAvgStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{0}
}

func (m *LoadAvgStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadAvgStat.Unmarshal(m, b)
}
func (m *LoadAvgStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadAvgStat.Marshal(b, m, deterministic)
}
func (m *LoadAvgStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadAvgStat.Merge(m, src)
}
func (m *LoadAvgStat) XXX_Size() int {
	return xxx_messageInfo_LoadAvgStat.Size(m)
}
func (m *LoadAvgStat) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadAvgStat.DiscardUnknown(m)
}

var xxx_messageInfo_LoadAvgStat proto.InternalMessageInfo

func (m *LoadAvgStat) GetLoadAvg() float32 {
	if m != nil {
		return m.LoadAvg
	}
	return 0
}

type CpuStat struct {
	UserPr               float32  `protobuf:"fixed32,1,opt,name=user_pr,json=userPr,proto3" json:"user_pr,omitempty"`
	NicePr               float32  `protobuf:"fixed32,2,opt,name=nice_pr,json=nicePr,proto3" json:"nice_pr,omitempty"`
	SystemPr             float32  `protobuf:"fixed32,3,opt,name=system_pr,json=systemPr,proto3" json:"system_pr,omitempty"`
	IdlePr               float32  `protobuf:"fixed32,4,opt,name=idle_pr,json=idlePr,proto3" json:"idle_pr,omitempty"`
	IowaitPr             float32  `protobuf:"fixed32,5,opt,name=iowait_pr,json=iowaitPr,proto3" json:"iowait_pr,omitempty"`
	StealPr              float32  `protobuf:"fixed32,6,opt,name=steal_pr,json=stealPr,proto3" json:"steal_pr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpuStat) Reset()         { *m = CpuStat{} }
func (m *CpuStat) String() string { return proto.CompactTextString(m) }
func (*CpuStat) ProtoMessage()    {}
func (*CpuStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{1}
}

func (m *CpuStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpuStat.Unmarshal(m, b)
}
func (m *CpuStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpuStat.Marshal(b, m, deterministic)
}
func (m *CpuStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpuStat.Merge(m, src)
}
func (m *CpuStat) XXX_Size() int {
	return xxx_messageInfo_CpuStat.Size(m)
}
func (m *CpuStat) XXX_DiscardUnknown() {
	xxx_messageInfo_CpuStat.DiscardUnknown(m)
}

var xxx_messageInfo_CpuStat proto.InternalMessageInfo

func (m *CpuStat) GetUserPr() float32 {
	if m != nil {
		return m.UserPr
	}
	return 0
}

func (m *CpuStat) GetNicePr() float32 {
	if m != nil {
		return m.NicePr
	}
	return 0
}

func (m *CpuStat) GetSystemPr() float32 {
	if m != nil {
		return m.SystemPr
	}
	return 0
}

func (m *CpuStat) GetIdlePr() float32 {
	if m != nil {
		return m.IdlePr
	}
	return 0
}

func (m *CpuStat) GetIowaitPr() float32 {
	if m != nil {
		return m.IowaitPr
	}
	return 0
}

func (m *CpuStat) GetStealPr() float32 {
	if m != nil {
		return m.StealPr
	}
	return 0
}

type MemStat struct {
	MemTotal             uint64   `protobuf:"varint,1,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemFree              uint64   `protobuf:"varint,2,opt,name=mem_free,json=memFree,proto3" json:"mem_free,omitempty"`
	Buffers              uint64   `protobuf:"varint,3,opt,name=buffers,proto3" json:"buffers,omitempty"`
	Cached               uint64   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	SwapCached           uint64   `protobuf:"varint,5,opt,name=swap_cached,json=swapCached,proto3" json:"swap_cached,omitempty"`
	SwapTotal            uint64   `protobuf:"varint,6,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree             uint64   `protobuf:"varint,7,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	Active               uint64   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	Inactive             uint64   `protobuf:"varint,9,opt,name=inactive,proto3" json:"inactive,omitempty"`
	VmallocUsed          uint64   `protobuf:"varint,10,opt,name=vmalloc_used,json=vmallocUsed,proto3" json:"vmalloc_used,omitempty"`
	Mapped               uint64   `protobuf:"varint,11,opt,name=mapped,proto3" json:"mapped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemStat) Reset()         { *m = MemStat{} }
func (m *MemStat) String() string { return proto.CompactTextString(m) }
func (*MemStat) ProtoMessage()    {}
func (*MemStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{2}
}

func (m *MemStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemStat.Unmarshal(m, b)
}
func (m *MemStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemStat.Marshal(b, m, deterministic)
}
func (m *MemStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemStat.Merge(m, src)
}
func (m *MemStat) XXX_Size() int {
	return xxx_messageInfo_MemStat.Size(m)
}
func (m *MemStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MemStat.DiscardUnknown(m)
}

var xxx_messageInfo_MemStat proto.InternalMessageInfo

func (m *MemStat) GetMemTotal() uint64 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *MemStat) GetMemFree() uint64 {
	if m != nil {
		return m.MemFree
	}
	return 0
}

func (m *MemStat) GetBuffers() uint64 {
	if m != nil {
		return m.Buffers
	}
	return 0
}

func (m *MemStat) GetCached() uint64 {
	if m != nil {
		return m.Cached
	}
	return 0
}

func (m *MemStat) GetSwapCached() uint64 {
	if m != nil {
		return m.SwapCached
	}
	return 0
}

func (m *MemStat) GetSwapTotal() uint64 {
	if m != nil {
		return m.SwapTotal
	}
	return 0
}

func (m *MemStat) GetSwapFree() uint64 {
	if m != nil {
		return m.SwapFree
	}
	return 0
}

func (m *MemStat) GetActive() uint64 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *MemStat) GetInactive() uint64 {
	if m != nil {
		return m.Inactive
	}
	return 0
}

func (m *MemStat) GetVmallocUsed() uint64 {
	if m != nil {
		return m.VmallocUsed
	}
	return 0
}

func (m *MemStat) GetMapped() uint64 {
	if m != nil {
		return m.Mapped
	}
	return 0
}

type DiskStat struct {
	DiskLoad             map[string]*DiskStat_DiskLoad  `protobuf:"bytes,1,rep,name=disk_load,json=diskLoad,proto3" json:"disk_load,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DiskSpace            map[string]*DiskStat_DiskSpace `protobuf:"bytes,2,rep,name=disk_space,json=diskSpace,proto3" json:"disk_space,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DiskStat) Reset()         { *m = DiskStat{} }
func (m *DiskStat) String() string { return proto.CompactTextString(m) }
func (*DiskStat) ProtoMessage()    {}
func (*DiskStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{3}
}

func (m *DiskStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStat.Unmarshal(m, b)
}
func (m *DiskStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStat.Marshal(b, m, deterministic)
}
func (m *DiskStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStat.Merge(m, src)
}
func (m *DiskStat) XXX_Size() int {
	return xxx_messageInfo_DiskStat.Size(m)
}
func (m *DiskStat) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStat.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStat proto.InternalMessageInfo

func (m *DiskStat) GetDiskLoad() map[string]*DiskStat_DiskLoad {
	if m != nil {
		return m.DiskLoad
	}
	return nil
}

func (m *DiskStat) GetDiskSpace() map[string]*DiskStat_DiskSpace {
	if m != nil {
		return m.DiskSpace
	}
	return nil
}

type DiskStat_DiskLoad struct {
	Tps                  float64  `protobuf:"fixed64,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Rps                  float64  `protobuf:"fixed64,2,opt,name=rps,proto3" json:"rps,omitempty"`
	Wps                  float64  `protobuf:"fixed64,3,opt,name=wps,proto3" json:"wps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskStat_DiskLoad) Reset()         { *m = DiskStat_DiskLoad{} }
func (m *DiskStat_DiskLoad) String() string { return proto.CompactTextString(m) }
func (*DiskStat_DiskLoad) ProtoMessage()    {}
func (*DiskStat_DiskLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{3, 0}
}

func (m *DiskStat_DiskLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStat_DiskLoad.Unmarshal(m, b)
}
func (m *DiskStat_DiskLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStat_DiskLoad.Marshal(b, m, deterministic)
}
func (m *DiskStat_DiskLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStat_DiskLoad.Merge(m, src)
}
func (m *DiskStat_DiskLoad) XXX_Size() int {
	return xxx_messageInfo_DiskStat_DiskLoad.Size(m)
}
func (m *DiskStat_DiskLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStat_DiskLoad.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStat_DiskLoad proto.InternalMessageInfo

func (m *DiskStat_DiskLoad) GetTps() float64 {
	if m != nil {
		return m.Tps
	}
	return 0
}

func (m *DiskStat_DiskLoad) GetRps() float64 {
	if m != nil {
		return m.Rps
	}
	return 0
}

func (m *DiskStat_DiskLoad) GetWps() float64 {
	if m != nil {
		return m.Wps
	}
	return 0
}

type DiskStat_DiskSpace struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used                 int64    `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Available            int64    `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Inodes               int64    `protobuf:"varint,4,opt,name=inodes,proto3" json:"inodes,omitempty"`
	PercentUsed          int64    `protobuf:"varint,5,opt,name=percent_used,json=percentUsed,proto3" json:"percent_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskStat_DiskSpace) Reset()         { *m = DiskStat_DiskSpace{} }
func (m *DiskStat_DiskSpace) String() string { return proto.CompactTextString(m) }
func (*DiskStat_DiskSpace) ProtoMessage()    {}
func (*DiskStat_DiskSpace) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{3, 1}
}

func (m *DiskStat_DiskSpace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStat_DiskSpace.Unmarshal(m, b)
}
func (m *DiskStat_DiskSpace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStat_DiskSpace.Marshal(b, m, deterministic)
}
func (m *DiskStat_DiskSpace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStat_DiskSpace.Merge(m, src)
}
func (m *DiskStat_DiskSpace) XXX_Size() int {
	return xxx_messageInfo_DiskStat_DiskSpace.Size(m)
}
func (m *DiskStat_DiskSpace) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStat_DiskSpace.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStat_DiskSpace proto.InternalMessageInfo

func (m *DiskStat_DiskSpace) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskStat_DiskSpace) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *DiskStat_DiskSpace) GetAvailable() int64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *DiskStat_DiskSpace) GetInodes() int64 {
	if m != nil {
		return m.Inodes
	}
	return 0
}

func (m *DiskStat_DiskSpace) GetPercentUsed() int64 {
	if m != nil {
		return m.PercentUsed
	}
	return 0
}

type NetworkStat struct {
	ListenSockets        []*NetworkStat_ListenSocket `protobuf:"bytes,1,rep,name=listen_sockets,json=listenSockets,proto3" json:"listen_sockets,omitempty"`
	SocketStates         map[string]int32            `protobuf:"bytes,2,rep,name=socket_states,json=socketStates,proto3" json:"socket_states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *NetworkStat) Reset()         { *m = NetworkStat{} }
func (m *NetworkStat) String() string { return proto.CompactTextString(m) }
func (*NetworkStat) ProtoMessage()    {}
func (*NetworkStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{4}
}

func (m *NetworkStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStat.Unmarshal(m, b)
}
func (m *NetworkStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStat.Marshal(b, m, deterministic)
}
func (m *NetworkStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStat.Merge(m, src)
}
func (m *NetworkStat) XXX_Size() int {
	return xxx_messageInfo_NetworkStat.Size(m)
}
func (m *NetworkStat) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStat.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStat proto.InternalMessageInfo

func (m *NetworkStat) GetListenSockets() []*NetworkStat_ListenSocket {
	if m != nil {
		return m.ListenSockets
	}
	return nil
}

func (m *NetworkStat) GetSocketStates() map[string]int32 {
	if m != nil {
		return m.SocketStates
	}
	return nil
}

type NetworkStat_ListenSocket struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LocalAddress         string   `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	PeerAddress          string   `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	Process              string   `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkStat_ListenSocket) Reset()         { *m = NetworkStat_ListenSocket{} }
func (m *NetworkStat_ListenSocket) String() string { return proto.CompactTextString(m) }
func (*NetworkStat_ListenSocket) ProtoMessage()    {}
func (*NetworkStat_ListenSocket) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{4, 0}
}

func (m *NetworkStat_ListenSocket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStat_ListenSocket.Unmarshal(m, b)
}
func (m *NetworkStat_ListenSocket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStat_ListenSocket.Marshal(b, m, deterministic)
}
func (m *NetworkStat_ListenSocket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStat_ListenSocket.Merge(m, src)
}
func (m *NetworkStat_ListenSocket) XXX_Size() int {
	return xxx_messageInfo_NetworkStat_ListenSocket.Size(m)
}
func (m *NetworkStat_ListenSocket) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStat_ListenSocket.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStat_ListenSocket proto.InternalMessageInfo

func (m *NetworkStat_ListenSocket) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *NetworkStat_ListenSocket) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *NetworkStat_ListenSocket) GetPeerAddress() string {
	if m != nil {
		return m.PeerAddress
	}
	return ""
}

func (m *NetworkStat_ListenSocket) GetProcess() string {
	if m != nil {
		return m.Process
	}
	return ""
}

type FullStat struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Interval             *duration.Duration   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	LoadStat             *LoadAvgStat         `protobuf:"bytes,3,opt,name=load_stat,json=loadStat,proto3" json:"load_stat,omitempty"`
	CpuStat              *CpuStat             `protobuf:"bytes,4,opt,name=cpu_stat,json=cpuStat,proto3" json:"cpu_stat,omitempty"`
	MemStat              *MemStat             `protobuf:"bytes,5,opt,name=mem_stat,json=memStat,proto3" json:"mem_stat,omitempty"`
	DiskStat             *DiskStat            `protobuf:"bytes,6,opt,name=disk_stat,json=diskStat,proto3" json:"disk_stat,omitempty"`
	NetworkStat          *NetworkStat         `protobuf:"bytes,7,opt,name=network_stat,json=networkStat,proto3" json:"network_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FullStat) Reset()         { *m = FullStat{} }
func (m *FullStat) String() string { return proto.CompactTextString(m) }
func (*FullStat) ProtoMessage()    {}
func (*FullStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{5}
}

func (m *FullStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullStat.Unmarshal(m, b)
}
func (m *FullStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullStat.Marshal(b, m, deterministic)
}
func (m *FullStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullStat.Merge(m, src)
}
func (m *FullStat) XXX_Size() int {
	return xxx_messageInfo_FullStat.Size(m)
}
func (m *FullStat) XXX_DiscardUnknown() {
	xxx_messageInfo_FullStat.DiscardUnknown(m)
}

var xxx_messageInfo_FullStat proto.InternalMessageInfo

func (m *FullStat) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *FullStat) GetInterval() *duration.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *FullStat) GetLoadStat() *LoadAvgStat {
	if m != nil {
		return m.LoadStat
	}
	return nil
}

func (m *FullStat) GetCpuStat() *CpuStat {
	if m != nil {
		return m.CpuStat
	}
	return nil
}

func (m *FullStat) GetMemStat() *MemStat {
	if m != nil {
		return m.MemStat
	}
	return nil
}

func (m *FullStat) GetDiskStat() *DiskStat {
	if m != nil {
		return m.DiskStat
	}
	return nil
}

func (m *FullStat) GetNetworkStat() *NetworkStat {
	if m != nil {
		return m.NetworkStat
	}
	return nil
}

type ServiceStatRequest struct {
	Interval             *duration.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Avgwindow            *duration.Duration `protobuf:"bytes,2,opt,name=avgwindow,proto3" json:"avgwindow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ServiceStatRequest) Reset()         { *m = ServiceStatRequest{} }
func (m *ServiceStatRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceStatRequest) ProtoMessage()    {}
func (*ServiceStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{6}
}

func (m *ServiceStatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatRequest.Unmarshal(m, b)
}
func (m *ServiceStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatRequest.Marshal(b, m, deterministic)
}
func (m *ServiceStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatRequest.Merge(m, src)
}
func (m *ServiceStatRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceStatRequest.Size(m)
}
func (m *ServiceStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatRequest proto.InternalMessageInfo

func (m *ServiceStatRequest) GetInterval() *duration.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *ServiceStatRequest) GetAvgwindow() *duration.Duration {
	if m != nil {
		return m.Avgwindow
	}
	return nil
}

type ServiceStatResponse struct {
	FullStat             *FullStat `protobuf:"bytes,1,opt,name=full_stat,json=fullStat,proto3" json:"full_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServiceStatResponse) Reset()         { *m = ServiceStatResponse{} }
func (m *ServiceStatResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceStatResponse) ProtoMessage()    {}
func (*ServiceStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3b82526cdfd1e7, []int{7}
}

func (m *ServiceStatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatResponse.Unmarshal(m, b)
}
func (m *ServiceStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatResponse.Marshal(b, m, deterministic)
}
func (m *ServiceStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatResponse.Merge(m, src)
}
func (m *ServiceStatResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceStatResponse.Size(m)
}
func (m *ServiceStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatResponse proto.InternalMessageInfo

func (m *ServiceStatResponse) GetFullStat() *FullStat {
	if m != nil {
		return m.FullStat
	}
	return nil
}

func init() {
	proto.RegisterType((*LoadAvgStat)(nil), "systemstatserver.LoadAvgStat")
	proto.RegisterType((*CpuStat)(nil), "systemstatserver.CpuStat")
	proto.RegisterType((*MemStat)(nil), "systemstatserver.MemStat")
	proto.RegisterType((*DiskStat)(nil), "systemstatserver.DiskStat")
	proto.RegisterMapType((map[string]*DiskStat_DiskLoad)(nil), "systemstatserver.DiskStat.DiskLoadEntry")
	proto.RegisterMapType((map[string]*DiskStat_DiskSpace)(nil), "systemstatserver.DiskStat.DiskSpaceEntry")
	proto.RegisterType((*DiskStat_DiskLoad)(nil), "systemstatserver.DiskStat.DiskLoad")
	proto.RegisterType((*DiskStat_DiskSpace)(nil), "systemstatserver.DiskStat.DiskSpace")
	proto.RegisterType((*NetworkStat)(nil), "systemstatserver.NetworkStat")
	proto.RegisterMapType((map[string]int32)(nil), "systemstatserver.NetworkStat.SocketStatesEntry")
	proto.RegisterType((*NetworkStat_ListenSocket)(nil), "systemstatserver.NetworkStat.ListenSocket")
	proto.RegisterType((*FullStat)(nil), "systemstatserver.FullStat")
	proto.RegisterType((*ServiceStatRequest)(nil), "systemstatserver.ServiceStatRequest")
	proto.RegisterType((*ServiceStatResponse)(nil), "systemstatserver.ServiceStatResponse")
}

func init() {
	proto.RegisterFile("SystemStats.proto", fileDescriptor_1f3b82526cdfd1e7)
}

var fileDescriptor_1f3b82526cdfd1e7 = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4b, 0x73, 0x1b, 0x45,
	0x10, 0xae, 0xb5, 0x1e, 0x2b, 0xf5, 0xda, 0xa9, 0x64, 0x49, 0x05, 0x65, 0x21, 0x24, 0x28, 0x50,
	0x65, 0x38, 0xc8, 0x94, 0x09, 0x15, 0x30, 0x07, 0x12, 0xf2, 0x80, 0x43, 0x48, 0x99, 0x91, 0xb9,
	0x70, 0x11, 0xa3, 0xdd, 0x91, 0xd9, 0xf2, 0xec, 0x23, 0x33, 0xb3, 0x52, 0xf9, 0x4e, 0x71, 0xa2,
	0x38, 0xf1, 0x27, 0xb8, 0x73, 0xe7, 0xaf, 0x51, 0xdd, 0x3d, 0xb2, 0xa5, 0xc8, 0xc6, 0xbe, 0x4d,
	0xf7, 0xd7, 0x5f, 0xcf, 0xb7, 0xdd, 0xbd, 0xd3, 0x70, 0x6b, 0x7c, 0x6a, 0x9d, 0x2a, 0xc6, 0x4e,
	0x3a, 0x3b, 0xaa, 0x4d, 0xe5, 0xaa, 0xf8, 0xa6, 0x25, 0x97, 0x45, 0x97, 0x32, 0x73, 0x65, 0x92,
	0xfb, 0xc7, 0x55, 0x75, 0xac, 0xd5, 0x1e, 0xe1, 0xd3, 0x66, 0xb6, 0xe7, 0xf2, 0x42, 0x59, 0x27,
	0x8b, 0x9a, 0x29, 0xc9, 0x07, 0x6f, 0x07, 0x64, 0x8d, 0x91, 0x2e, 0xaf, 0x4a, 0xc6, 0x87, 0xbb,
	0x10, 0xbd, 0xaa, 0x64, 0xf6, 0x74, 0x7e, 0x8c, 0x17, 0xc5, 0x77, 0xa1, 0xa7, 0x2b, 0x99, 0x4d,
	0xe4, 0xfc, 0x78, 0x10, 0x3c, 0x08, 0x76, 0xb7, 0x44, 0xa8, 0x19, 0x1e, 0xfe, 0x1d, 0x40, 0xf8,
	0xac, 0x6e, 0x28, 0xec, 0x5d, 0x08, 0x1b, 0xab, 0xcc, 0xa4, 0x36, 0x3e, 0xaa, 0x8b, 0xe6, 0xa1,
	0x41, 0xa0, 0xcc, 0x53, 0x85, 0xc0, 0x16, 0x03, 0x68, 0x1e, 0x9a, 0xf8, 0x3d, 0xe8, 0xb3, 0x78,
	0x84, 0x5a, 0x04, 0xf5, 0xd8, 0xc1, 0xac, 0x3c, 0xd3, 0xc4, 0x6a, 0x33, 0x0b, 0x4d, 0x66, 0xe5,
	0xd5, 0x42, 0xe6, 0x0e, 0xa1, 0x0e, 0xb3, 0xd8, 0x71, 0x68, 0x50, 0xab, 0x75, 0x4a, 0x6a, 0xc4,
	0xba, 0xac, 0x95, 0xec, 0x43, 0x33, 0xfc, 0x77, 0x0b, 0xc2, 0x1f, 0xb8, 0x76, 0x98, 0xa3, 0x50,
	0xc5, 0xc4, 0x55, 0x4e, 0x6a, 0x52, 0xdb, 0x16, 0xbd, 0x42, 0x15, 0x47, 0x68, 0x63, 0x0e, 0x04,
	0x67, 0x46, 0x29, 0x12, 0xdc, 0x16, 0x61, 0xa1, 0x8a, 0x97, 0x46, 0xa9, 0x78, 0x00, 0xe1, 0xb4,
	0x99, 0xcd, 0x94, 0xb1, 0xa4, 0xb7, 0x2d, 0x96, 0x66, 0x7c, 0x07, 0xba, 0xa9, 0x4c, 0x7f, 0x55,
	0x19, 0xa9, 0x6d, 0x0b, 0x6f, 0xc5, 0xf7, 0x21, 0xb2, 0x0b, 0x59, 0x4f, 0x3c, 0xd8, 0x21, 0x10,
	0xd0, 0xf5, 0x8c, 0x03, 0xee, 0x01, 0x59, 0x5e, 0x4b, 0x97, 0xf0, 0x3e, 0x7a, 0x58, 0x0c, 0xd6,
	0x08, 0x61, 0x52, 0x13, 0xb2, 0x52, 0x74, 0x90, 0x9c, 0x3b, 0xd0, 0x95, 0xa9, 0xcb, 0xe7, 0x6a,
	0xd0, 0xe3, 0x4b, 0xd9, 0x8a, 0x13, 0xe8, 0xe5, 0xa5, 0x47, 0xfa, 0xcc, 0x59, 0xda, 0xf1, 0x87,
	0xb0, 0x3d, 0x2f, 0xa4, 0xd6, 0x55, 0x3a, 0x69, 0xac, 0xca, 0x06, 0x40, 0x78, 0xe4, 0x7d, 0x3f,
	0x59, 0x95, 0x61, 0xda, 0x42, 0xd6, 0xb5, 0xca, 0x06, 0x11, 0xa7, 0x65, 0x6b, 0xf8, 0x4f, 0x1b,
	0x7a, 0xcf, 0x73, 0x7b, 0x42, 0x25, 0x7c, 0x01, 0xfd, 0x2c, 0xb7, 0x27, 0x13, 0x1c, 0x85, 0x41,
	0xf0, 0xa0, 0xb5, 0x1b, 0xed, 0xef, 0x8e, 0xde, 0x9e, 0xc5, 0xd1, 0x32, 0x9c, 0x0e, 0x38, 0x54,
	0x2f, 0x4a, 0x67, 0x4e, 0x45, 0x2f, 0xf3, 0x66, 0xfc, 0x3d, 0x00, 0xa5, 0xb1, 0xb5, 0x4c, 0xb1,
	0xdc, 0x98, 0xe7, 0x93, 0x2b, 0xf2, 0x8c, 0x31, 0x96, 0x13, 0x91, 0x06, 0xb2, 0x93, 0x27, 0x2c,
	0x8e, 0xb2, 0xde, 0x84, 0x96, 0xab, 0x2d, 0x75, 0x36, 0x10, 0x78, 0x44, 0x8f, 0xa9, 0x2d, 0xf5,
	0x33, 0x10, 0x78, 0x44, 0xcf, 0xa2, 0xe6, 0x3e, 0x06, 0x02, 0x8f, 0xc9, 0x9f, 0x01, 0xf4, 0xcf,
	0xf2, 0xc7, 0xb7, 0xa1, 0x73, 0x3e, 0x1f, 0x2d, 0xc1, 0x46, 0x1c, 0x43, 0x9b, 0xca, 0xb6, 0x45,
	0x4e, 0x3a, 0xc7, 0xef, 0x43, 0x5f, 0xce, 0x65, 0xae, 0xe5, 0x54, 0x2b, 0xca, 0xd7, 0x12, 0xe7,
	0x0e, 0xac, 0x66, 0x5e, 0x56, 0x99, 0xb2, 0x34, 0x19, 0x2d, 0xe1, 0x2d, 0x6c, 0x44, 0xad, 0x4c,
	0xaa, 0x4a, 0xc7, 0x8d, 0xe8, 0x10, 0x1a, 0x79, 0x1f, 0x36, 0x22, 0xf9, 0x05, 0x76, 0xd6, 0xea,
	0x86, 0x9a, 0x4f, 0xd4, 0x29, 0x29, 0xea, 0x0b, 0x3c, 0xc6, 0x5f, 0x41, 0x67, 0x2e, 0x75, 0xc3,
	0x93, 0x1a, 0xed, 0x3f, 0xbc, 0x46, 0x0b, 0x04, 0x33, 0x0e, 0xb6, 0xbe, 0x0c, 0x92, 0x29, 0xdc,
	0x58, 0xaf, 0xe8, 0x05, 0x57, 0x1c, 0xac, 0x5f, 0xf1, 0xd1, 0x75, 0xba, 0xb3, 0x72, 0xc7, 0xf0,
	0xf7, 0x16, 0x44, 0xaf, 0x95, 0x5b, 0x54, 0x86, 0x27, 0xe7, 0x47, 0xb8, 0xa1, 0x73, 0xeb, 0x54,
	0x39, 0xb1, 0x55, 0x7a, 0xa2, 0x9c, 0xf5, 0xe3, 0xf3, 0xe9, 0x66, 0xe2, 0x15, 0xda, 0xe8, 0x15,
	0x71, 0xc6, 0x44, 0x11, 0x3b, 0x7a, 0xc5, 0xb2, 0xf1, 0x11, 0xec, 0x70, 0xae, 0x09, 0x92, 0x95,
	0xf5, 0x83, 0xb4, 0xf7, 0xff, 0x19, 0x99, 0x3d, 0x26, 0x06, 0x8f, 0xd3, 0xb6, 0x5d, 0x71, 0x25,
	0x7f, 0x04, 0xb0, 0xbd, 0x7a, 0x2b, 0xfe, 0x57, 0xf4, 0x42, 0xa6, 0x95, 0xf6, 0x05, 0x3a, 0xb3,
	0xe3, 0x87, 0xb0, 0xa3, 0xab, 0x54, 0xea, 0x89, 0xcc, 0x32, 0xa3, 0x2c, 0x8f, 0x5a, 0x5f, 0x6c,
	0x93, 0xf3, 0x29, 0xfb, 0xb8, 0xe7, 0xca, 0x9c, 0xc5, 0xb4, 0x28, 0x26, 0x42, 0xdf, 0x32, 0x64,
	0x00, 0x61, 0x6d, 0xaa, 0x14, 0xd1, 0x36, 0xa1, 0x4b, 0x33, 0xf9, 0x06, 0x6e, 0x6d, 0x28, 0xbe,
	0xa0, 0x5d, 0xb7, 0x57, 0xdb, 0xd5, 0x59, 0x6d, 0xc4, 0x5f, 0x2d, 0xe8, 0xbd, 0x6c, 0xb4, 0xa6,
	0x2e, 0x8c, 0xa0, 0x8d, 0x7b, 0x81, 0x98, 0xd1, 0x7e, 0x32, 0xe2, 0x9d, 0x30, 0x5a, 0xee, 0x84,
	0xd1, 0xd1, 0x72, 0x69, 0x08, 0x8a, 0x8b, 0xbf, 0xc0, 0x37, 0xc5, 0x29, 0x33, 0x97, 0xda, 0x0f,
	0xc2, 0xdd, 0x0d, 0xce, 0x73, 0xbf, 0x47, 0xc4, 0x59, 0x68, 0x7c, 0x00, 0x7d, 0x5a, 0x1e, 0xd8,
	0x02, 0xfa, 0xdc, 0x68, 0xff, 0xde, 0x66, 0x57, 0x56, 0xd6, 0x8d, 0xa0, 0x65, 0x43, 0x12, 0x1f,
	0x41, 0x2f, 0xad, 0x1b, 0xa6, 0xb6, 0xfd, 0x95, 0x1b, 0x54, 0xbf, 0x7e, 0x44, 0x98, 0xfa, 0x3d,
	0xf4, 0x88, 0x9f, 0x6f, 0x62, 0x75, 0x2e, 0x63, 0xf9, 0x45, 0x40, 0x2f, 0x3b, 0xb1, 0x1e, 0xfb,
	0xe7, 0x8c, 0x68, 0x5d, 0x5f, 0x93, 0x4b, 0x07, 0x9d, 0x1f, 0x30, 0x22, 0x3e, 0x81, 0xed, 0x92,
	0x67, 0x8a, 0xb9, 0xe1, 0x65, 0xdf, 0xb8, 0x32, 0x79, 0x22, 0x2a, 0xcf, 0x8d, 0xe1, 0x6f, 0x01,
	0xc4, 0x63, 0x65, 0xe6, 0x79, 0xaa, 0x08, 0x54, 0x6f, 0x1a, 0x65, 0xdd, 0x5a, 0xc1, 0x83, 0xeb,
	0x17, 0xfc, 0x31, 0x3e, 0x46, 0xc7, 0x8b, 0xbc, 0xcc, 0xaa, 0xc5, 0xd5, 0x8d, 0x3a, 0x8f, 0x1d,
	0xbe, 0x86, 0x77, 0xd6, 0x54, 0xd8, 0xba, 0x2a, 0xad, 0xc2, 0x7c, 0xb3, 0x46, 0x6b, 0xfe, 0xb8,
	0xe0, 0xb2, 0xc2, 0x2c, 0xc7, 0x4a, 0xf4, 0x66, 0xfe, 0xb4, 0xff, 0x06, 0xa2, 0x95, 0x7c, 0xf1,
	0x14, 0x6e, 0x7d, 0xa7, 0xdc, 0x32, 0x6e, 0xec, 0x8c, 0x92, 0x45, 0x7c, 0xc1, 0x5b, 0xb2, 0x59,
	0x89, 0xe4, 0xe3, 0x2b, 0xa2, 0x58, 0xe9, 0x67, 0xc1, 0xb7, 0xe1, 0xcf, 0x9d, 0xd1, 0xde, 0xd7,
	0xf5, 0x74, 0xda, 0xa5, 0x2f, 0xfd, 0xfc, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x7d, 0x60,
	0xc0, 0x30, 0x09, 0x00, 0x00,
}
